version: '3.9'
services:
  ner:
    container_name: ner
    build: ./ner
    ports:
      - '443:443'
    networks:
      - backend

  stanford-ner:
    container_name: stanford-ner
    build: ./stanford-ner
    ports:
      - '8080:8080'
    networks:
      - backend

  scraper:
    container_name: scraper
    build: ./scraper
    ports:
      - '80:80'
    networks:
      - backend

  tor-proxy:
    image: dperson/torproxy
    container_name: tor-proxy
    ports:
      - '8118:8118'
    expose:
      - 8118
    networks:
      - backend

  app:
    container_name: app
    restart: always
    build: .
    ports:
      - '8081:8081'
    networks:
      - backend

  # ner:
  #   container_name: ner
  #   build: ./server/src/utils/helpers/analysis/NER
  #   ports:
  #     - '8080:8080'
  #   networks:
  #     - frontend
  #     - backend

  # darknet:
  #   image: dperson/torproxy
  #   container_name: tor-proxy
  #   ports:
  #     - '8118:8118'
  #   expose:
  #     - 8118
  #   networks:
  #     - frontend
  #     - backend

networks:
  # frontend:
  #   driver: bridge
  backend:
    driver: bridge
