version: '3.9'
services:
  app:
    container_name: pastes
    restart: always
    build: .
    ports:
      - '8081:8081'
    networks:
      - frontend
      - backend

  ner:
    container_name: ner
    build: ./server/src/utils/helpers/analysis/NER
    ports:
      - '8080:8080'
    networks:
      - frontend
      - backend

  darknet:
    image: dperson/torproxy
    container_name: tor-proxy
    ports:
      - '8118:8118'
    expose:
      - 8118
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
